# Generated by Django 5.1.7 on 2025-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='upload_to',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
    ]
