# Generated by Django 5.1.7 on 2025-03-19 08:28

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='media/blog/'),
        ),
    ]
